version: '3'
services:

  www:
    build: .
    ports: 
        - "80:80"
    volumes:
        - ./public-html:/var/www/html
    links:
        - mariadb
    networks:
      - default

  mariadb:
    image: mariadb:10.1
    container_name: docker-apache-mariadb-mariadb
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=simplon
      - MYSQL_USER=simplon
      - MYSQL_PASSWORD=simplon
    ports:
      - "3307:3306"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: docker-apache-mariadb-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links: 
          - mariadb:mariadb
      ports:
          - 8001:80
      environment:
          MYSQL_USER: simplon
          MYSQL_PASSWORD: simplon
          MYSQL_ROOT_PASSWORD: 
          PMA_HOST: mysql
          PMA_PORT: 3307
          
  sass:
    image: "node:10"
    container_name: trombinoscope-sass
    working_dir: /application
    volumes:
      - ./:/application
    ports:
      - "8000:8000"
    command: >
      bash -c "npm install node-sass --save
      && ./node_modules/.bin/node-sass scss -o  public-html/css -w --source-map public-html/css"